# Rebind prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# scroll amount
bind -T copy-mode-vi WheelUpPane select-pane \; send-keys -X -N 1 scroll-up
bind -T copy-mode-vi WheelDownPane select-pane \; send-keys -X -N 1 scroll-down

# Mouse support: click panes, resize panes, scroll
set -g mouse on

# Better terminal colors
set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm-256color:RGB"

# More scrollback
set -g history-limit 50000

# Reload config quickly
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Vim-style pane navigation with prefix + hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vi-style copy mode
setw -g mode-keys vi

# Copy selection with y in copy mode
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# New windows/panes open in the current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim style copy
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel


# Plugins
set -g @plugin 'tmux-plugins/tpm'

# Smooth scroll
set -g @plugin 'azorng/tmux-smooth-scroll'

# Ressurect plugin
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'

# Tmux Continuum
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'
set -g status-right 'Continuum status: #{continuum_status}'

# Tmux pluggin manager - correctly at bottom
run '~/.tmux/plugins/tpm/tpm'

